# Filter name strings
LOG_FILTER = 'LOG_FILTER'
EVENT_FILTER = 'EVENT_FILTER'
QTRACE_NON_REGEX = 'QTRACE_NON_REGEX'
QTRACE_REGEX = 'QTRACE_REGEX'
F3S_NON_REGEX = 'F3S_NON_REGEX'
F3S_REGEX = 'F3S_REGEX'
DEBUG_MSG_ID = 'DEBUG_MSG_ID'
KEYWORDS_FILTER = 'KEYWORDS_FILTER'
ANALYZER_FILTER = 'ANALYZER_FILTER'

# Log filter mask
filter_mask = {
    LOG_FILTER: [0xB821, 0x1568, 0x1569, 0x156A, 0x156C, 0xB800, 0xB801, 0xB808, 
                 0xB809, 0xB80A, 0xB80B, 0xB814, 0xB890, 0x1CD0],
    EVENT_FILTER: [3188, 3190],
    QTRACE_NON_REGEX: [],
    QTRACE_REGEX: [],
    F3S_NON_REGEX: [],
    F3S_REGEX: [],
    DEBUG_MSG_ID: {},
    KEYWORDS_FILTER: [],
    ANALYZER_FILTER: []
}